// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/Game.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Team struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	Away                 string   `protobuf:"bytes,2,opt,name=away,proto3" json:"away,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f8decbf488d309b, []int{0}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *Team) GetAway() string {
	if m != nil {
		return m.Away
	}
	return ""
}

type Game struct {
	Team                 *Team    `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	Venue                string   `protobuf:"bytes,2,opt,name=venue,proto3" json:"venue,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f8decbf488d309b, []int{1}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *Game) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

func (m *Game) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func init() {
	proto.RegisterType((*Team)(nil), "proto.Team")
	proto.RegisterType((*Game)(nil), "proto.Game")
}

func init() { proto.RegisterFile("proto/Game.proto", fileDescriptor_5f8decbf488d309b) }

var fileDescriptor_5f8decbf488d309b = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x77, 0x4f, 0xcc, 0x4d, 0xd5, 0x03, 0x33, 0x85, 0x58, 0xc1, 0x94, 0x92, 0x1e, 0x17,
	0x4b, 0x48, 0x6a, 0x62, 0xae, 0x90, 0x10, 0x17, 0x4b, 0x46, 0x7e, 0x6e, 0xaa, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x98, 0x0d, 0x12, 0x4b, 0x2c, 0x4f, 0xac, 0x94, 0x60, 0x82, 0x88, 0x81,
	0xd8, 0x4a, 0x81, 0x5c, 0x2c, 0x20, 0x43, 0x84, 0xe4, 0xb9, 0x58, 0x4a, 0x52, 0x13, 0x73, 0xc1,
	0xea, 0xb9, 0x8d, 0xb8, 0x21, 0x86, 0xea, 0x81, 0x8c, 0x0a, 0x02, 0x4b, 0x08, 0x89, 0x70, 0xb1,
	0x96, 0xa5, 0xe6, 0x95, 0xa6, 0x42, 0x75, 0x43, 0x38, 0x20, 0x23, 0x53, 0x12, 0x4b, 0x52, 0x25,
	0x98, 0x21, 0x46, 0x82, 0xd8, 0x49, 0x6c, 0x60, 0xbd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xe6, 0x95, 0x97, 0xc8, 0xa4, 0x00, 0x00, 0x00,
}
